# 服务端口号
server:
  port: 8401

# 应用名
spring:
  application:
    name: cloud-alibaba-sentinel-service   # 多服务集群，有相同的应用名
  cloud:
    nacos:
      discovery:
        # nacos 服务注册中心地址
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 配置 sentinel-dashboard 地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

# 设置日志记录级别：trace < debug < info < warn < error
logging:
  level:
    com:
      springcloud:
        project: debug

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # 默认 health、info




