# 服务端口号
server:
  port: 8310

# 应用名
spring:
  application:
    name: cloud-nacos-consumer-service   # 多服务集群，有相同的应用名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 配置 nacos 地址

# 服务提供者地址：消费者将要去访问的微服务名称（注册进 nacos 的服务提供者）
service-url:
  nacos-provider-service: http://cloud-nacos-provider-service

# 设置日志记录级别：trace < debug < info < warn < error
logging:
  level:
    com:
      springcloud:
        project: debug

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # 默认 health、info
